spring:
  application:
    name: rest-api-finances

  datasource:
    url: jdbc:oracle:thin:@//oracle-db:1521/FREE
    username: dev_user
    password: db314159
    driver-class-name: oracle.jdbc.OracleDriver

  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    pool-name: MyOraclePool

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
  #        show_sql: true
  #      javax:
  #        persistence:
  #          schema-generation:
  #            scripts:
  #              action: create
  #              create-target: target/schema_inicial.sql

  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true


logging:
  level:
    com.abner: DEBUG

server:
  port: 8080 # Porta onde sua API vai rodar