spring:
  application:
    name: rest-api-finances

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    pool-name: MyOraclePool

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DB_USERNAME}
        format_sql: true
  #        show_sql: true
  #      javax:
  #        persistence:
  #          schema-generation:
  #            scripts:
  #              action: create
  #              create-target: target/schema_inicial.sql

  flyway:
    enabled: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
#    schemas: ${FLYWAY_SCHEMAS}
#    baseline-on-migrate: true
#    repair-on-migrate: true


logging:
  level:
    com.abner: DEBUG

server:
  port: ${SERVER_PORT}