version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    volumes:
      - ./init-db:/opt/oracle/scripts/startup
      - oracle_data:/opt/oracle/oradata
    container_name: oracle-db
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD-SHELL", "echo 'exit' | sqlplus -L dev_user/db314159@FREEPDB1"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 30s

  spring-app:
    build: .
    env_file: .env
    container_name: spring-app
    volumes:
      - .:/app
      - "C:\\Users\\ricks\\.m2:/root/.m2"
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      oracle-db:
        condition: service_healthy # Espera o banco estar pronto para subir o Spring

volumes:
  oracle_data: